import "../pages/index.css";
import Popup from "../components/Popup.js";
import PopupVid from "../components/PopupVid.js";
import svgMap from "svgmap";
import "svgmap/dist/svgMap.min.css";
import validation from "../components/Validation";

window.scroll({
  top: 100,
  left: 100,
  behavior: "smooth",
});

document.querySelectorAll('a[href^="#"]').forEach((anchor) => {
  anchor.addEventListener("click", function (e) {
    e.preventDefault();
    document.querySelector(this.getAttribute("href")).scrollIntoView({
      behavior: "smooth",
    });
  });
});

const popupVid = new PopupVid({ selector: ".popup__vid" });

const popup = new Popup({
  popupSelector: "#popup",
  button: "#button1",
  buttonClose: ".popup__button",
});

const popup2 = new Popup({
  popupSelector: "#popup2",
  button: "#button2",
  buttonClose: "#button3",
});

popup.fillInfo(
  "Ani Petrichor",
  "Data Analyst",
  "Ani Petrichor is a Brooklyn-based data analyst. She has a background in operations & logistics in the sustainability food sector, primarily working to bring locally farmed ingredients to urban residents. She believes that big data can be used to effect good in the world."
);

popup2.fillUserInfo(
  "Kurtney Joseph",
  "Software Engineer",
  "Kurtney Joseph is an Orlando based software engineer who aims to provide companies and local businesses with effective solutions though web development."
);

popupVid.setEventListeners();
popup.setEventListeners();
popup2.setEventListeners();

new svgMap({
  targetElementID: "svgMap",
  data: {
    data: {
      MW: {
        name: "MegaWatt Capacity:",
        thresholdMax: 50000,
        thresholdMin: 1000,
      },
      SF: {
        name: "Solar Farms:",
      },
    },
    applyData: "MW",
    values: {
      US: { MW: 147086, color: "#FFFFE0", SF: 1359 },
      CN: { MW: 139994, color: "#FFFFE0", SF: 2735 },
      IN: { MW: 59271, color: "#FED8B1", SF: 461 },
      AU: { MW: 55702, color: "#FED8B1", SF: 208 },
      GR: { MW: 43046, color: "#FED8B1", SF: 524 },
      BR: { MW: 36238, color: "#FED8B1", SF: 683 },
      MX: { MW: 20858, color: "#FED8B1", SF: 236 },
      ES: { MW: 20606, color: "#FED8B1", SF: 203 },
      CO: { MW: 19054, color: "#FED8B1", SF: 178 },
      OM: { MW: 15430, color: "#FED8B1", SF: 10 },
      MA: { MW: 14132, color: "#FED8B1", SF: 25 },
      CL: { MW: 13967, color: "#FED8B1", SF: 87 },
      VN: { MW: 15430, color: "#FED8B1", SF: 155 },
      PH: { MW: 11696, color: "#FED8B1", SF: 127 },
      JP: { MW: 10099, color: "#FED8B1", SF: 229 },
      KW: { MW: 9520, color: "#90EE90", SF: 6 },
      GB: { MW: 8314, color: "#90EE90", SF: 197 },
      MM: { MW: 6050, color: "#90EE90", SF: 4 },
      AE: { MW: 5620, color: "#90EE90", SF: 14 },
      SA: { MW: 4886, color: "#90EE90", SF: 19 },
      DZ: { MW: 4455, color: "#90EE90", SF: 22 },
      DE: { MW: 4433, color: "#90EE90", SF: 88 },
      ZA: { MW: 3742, color: "#90EE90", SF: 49 },
      KR: { MW: 3385, color: "#90EE90", SF: 17 },
      AF: { MW: 3135, color: "#90EE90", SF: 5 },
      PT: { MW: 2895, color: "#90EE90", SF: 32 },
      BD: { MW: 2793, color: "#90EE90", SF: 40 },
      ID: { MW: 2565, color: "#90EE90", SF: 6 },
      CA: { MW: 2527, color: "#90EE90", SF: 44 },
      FR: { MW: 2489, color: "#90EE90", SF: 32 },
      EG: { MW: 2286, color: "#90EE90", SF: 40 },
      MY: { MW: 2138, color: "#90EE90", SF: 40 },
      IT: { MW: 2019, color: "#90EE90", SF: 38 },
      TR: { MW: 1777, color: "#90EE90", SF: 13 },
      TW: { MW: 1715, color: "#90EE90", SF: 14 },
      UA: { MW: 1703, color: "#90EE90", SF: 31 },
      TH: { MW: 1699, color: "#90EE90", SF: 11 },
      GH: { MW: 1662, color: "#90EE90", SF: 20 },
      JO: { MW: 1648, color: "#90EE90", SF: 28 },
      DK: { MW: 1471, color: "#90EE90", SF: 20 },
      IQ: { MW: 1300, color: "#90EE90", SF: 2 },
      LK: { MW: 1270, color: "#90EE90", SF: 6 },
      RO: { MW: 1263, color: "#90EE90", SF: 21 },
      NZ: { MW: 1211, color: "#90EE90", SF: 11 },
      RU: { MW: 1134, color: "#90EE90", SF: 35 },
      ET: { MW: 1100, color: "#90EE90", SF: 3 },
      KZ: { MW: 1087, color: "#90EE90", SF: 19 },
      AR: { MW: 1001, color: "#90EE90", SF: 13 },
      NL: { MW: 1000, color: "#90EE90", SF: 21 },
      PL: { MW: 918, color: "#CBC3E3", SF: 9 },
      PE: { MW: 904, color: "#CBC3E3", SF: 11 },
      QA: { MW: 815, color: "#CBC3E3", SF: 3 },
      IL: { MW: 788, color: "#CBC3E3", SF: 9 },
      DO: { MW: 714, color: "#CBC3E3", SF: 12 },
      TN: { MW: 700, color: "#CBC3E3", SF: 13 },
      CD: { MW: 640, color: "#CBC3E3", SF: 3 },
      BA: { MW: 632, color: "#CBC3E3", SF: 12 },
      HN: { MW: 572, color: "#CBC3E3", SF: 15 },
      BG: { MW: 549, color: "#CBC3E3", SF: 9 },
      MK: { MW: 530, color: "#CBC3E3", SF: 3 },
      KE: { MW: 514, color: "#CBC3E3", SF: 12 },
      KH: { MW: 485, color: "#CBC3E3", SF: 12 },
      PK: { MW: 450, color: "#CBC3E3", SF: 3 },
      AL: { MW: 390, color: "#CBC3E3", SF: 5 },
      EC: { MW: 362, color: "#CBC3E3", SF: 4 },
      PR: { MW: 342, color: "#CBC3E3", SF: 5 },
      SY: { MW: 338, color: "#CBC3E3", SF: 3 },
      HU: { MW: 314, color: "#CBC3E3", SF: 10 },
      RS: { MW: 280, color: "#CBC3E3", SF: 5 },
      SG: { MW: 274, color: "#CBC3E3", SF: 4 },
      SV: { MW: 265, color: "#CBC3E3", SF: 5 },
      AZ: { MW: 250, color: "#CBC3E3", SF: 2 },
      BF: { MW: 241, color: "#CBC3E3", SF: 8 },
      BE: { MW: 233, color: "#CBC3E3", SF: 5 },
      SN: { MW: 212, color: "#CBC3E3", SF: 8 },
      AM: { MW: 200, color: "#CBC3E3", SF: 1 },
      GU: { MW: 196, color: "#CBC3E3", SF: 5 },
      UY: { MW: 190, color: "#CBC3E3", SF: 5 },
      XK: { MW: 180, color: "#CBC3E3", SF: 2 },
      NI: { MW: 180, color: "#CBC3E3", SF: 5 },
      PA: { MW: 177, color: "#CBC3E3", SF: 3 },
      BO: { MW: 160, color: "#CBC3E3", SF: 3 },
      TD: { MW: 160, color: "#CBC3E3", SF: 4 },
      MW: { MW: 151, color: "#CBC3E3", SF: 4 },
      GM: { MW: 150, color: "#CBC3E3", SF: 2 },
      TT: { MW: 150, color: "#CBC3E3", SF: 2 },
      EH: { MW: 105, color: "#CBC3E3", SF: 2 },
      BH: { MW: 100, color: "#CBC3E3", SF: 1 },
      SZ: { MW: 100, color: "#CBC3E3", SF: 1 },
      VA: { MW: 100, color: "#CBC3E3", SF: 1 },
      ML: { MW: 100, color: "#CBC3E3", SF: 3 },
      UZ: { MW: 100, color: "#CBC3E3", SF: 1 },
      GT: { MW: 93, color: "#528AAE", SF: 2 },
      ZM: { MW: 88, color: "#528AAE", SF: 2 },
      CZ: { MW: 87, color: "#528AAE", SF: 3 },
      JM: { MW: 72, color: "#528AAE", SF: 2 },
      MR: { MW: 65, color: "#528AAE", SF: 2 },
      LA: { MW: 64, color: "#528AAE", SF: 1 },
      SK: { MW: 58, color: "#528AAE", SF: 1 },
      UG: { MW: 57, color: "#528AAE", SF: 2 },
      BY: { MW: 55, color: "#528AAE", SF: 1 },
      GF: { MW: 55, color: "#528AAE", SF: 1 },
      BJ: { MW: 50, color: "#528AAE", SF: 2 },
      TG: { MW: 50, color: "#528AAE", SF: 2 },
      NA: { MW: 46, color: "#528AAE", SF: 1 },
      SE: { MW: 46, color: "#528AAE", SF: 2 },
      MZ: { MW: 40, color: "#528AAE", SF: 1 },
      CU: { MW: 39, color: "#528AAE", SF: 1 },
      KN: { MW: 38, color: "#528AAE", SF: 1 },
      MN: { MW: 30, color: "#528AAE", SF: 1 },
      NC: { MW: 30, color: "#528AAE", SF: 1 },
      CF: { MW: 25, color: "#528AAE", SF: 1 },
      NP: { MW: 25, color: "#528AAE", SF: 1 },
      ZW: { MW: 25, color: "#528AAE", SF: 1 },
      AT: { MW: 24, color: "#528AAE", SF: 1 },
      IR: { MW: 20, color: "#528AAE", SF: 1 },
      MG: { MW: 20, color: "#528AAE", SF: 1 },
      SS: { MW: 20, color: "#528AAE", SF: 1 },
      SO: { MW: 10, color: "#528AAE", SF: 1 },
      SD: { MW: 10, color: "#528AAE", SF: 1 },
      GL: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      NO: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      HT: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      VE: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      PY: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      CR: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      GY: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      SR: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      FK: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      PG: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      SB: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      FI: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      EE: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      LV: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      LT: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      IS: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      IE: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      HR: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      PG: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      CH: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      SI: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      MD: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      ME: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      GE: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      TJ: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      TM: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      KP: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      KG: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      YE: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      LY: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      AO: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      BW: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      TZ: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      ER: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      LS: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      NE: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      CG: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      GA: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      NG: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      CM: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      GQ: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      PF: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      BZ: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      BS: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      BI: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      RW: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      CY: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      LB: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      PS: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      MT: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      CI: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      LR: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      GN: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      GW: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      SL: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      ST: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      TL: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
      FO: { MW: "No megawatt capacity", color: "#FFCCCB", SF: 0 },
    },
  },
});
